services:
  db:
    image: postgres:16-alpine
    container_name: cinema_postgres
    restart: always
    environment:
      POSTGRES_USER: cinema_user
      POSTGRES_PASSWORD: cinema_password
      POSTGRES_DB: cinema_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: