name: Docker CI

on:
  push:
    branches: ["main"]
    paths:
      - "backend/**"
      - "frontend/**"
      - "docker-compose.yml"
  pull_request:
    branches: ["main"]
    paths:
      - "backend/**"
      - "frontend/**"
      - "docker-compose.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Build
        run: docker compose build
